### ISSUE TITLE
JIO sim not working on Redmi y2 with stock and custom ROM

### ISSUE THREAD

**Issue by ahammedshamil** [ItsVixano-releases/LineageOS_ysl#4]
I have a **Redmi y2** device with a **JIO** sim card. I tried to use it on the **stock ROM** but it did not work. Then I downloaded and installed a **custom ROM** from [**LineageOS 20**](https://github.com/ItsVixano-releases/LineageOS_ysl/releases/) but it still did not work.

**The issues I faced are:**

- **SMS** not working at all
- **VoLTE** only working when network selection is set to LTE only mode
- **Mobile data** working normally

Please help me fix this issue. Thank you.

**Comment by ItsVixano** [comment]
Hi, last time i tried LTE on my device, it worked fine (including sms and volte)

Currently i'm reworking a lot of stuffs on the device trees

**Comment by Ashatul** [comment]
Your firmwere is corrupted any how , follow these step , and reinstalled complete firmwere by xiomi flash too, after that you can switch back to custom rom.
   Just download dummy.img from fastboot firmware miui 11.0.2.0 pefmixm

Paste it in your fastboot folder.
Open a command window in your fastboot folder.
Enable devoloper options in your phone.
Connect the phone to pc in fastboot mode.

Enter these commands:
Fastboot devices
Fastboot flash modemst1 dummy.img
Fastboot flash modemst2 dummy.img

**Comment by Ashatul** [comment]
You can mail me for more help.

**Comment by R0rt1z2** [comment]
stfu

**Comment by Ashatul** [comment]
Sorry??

**Comment by Ashatul** [comment]
@R0rt1z2 I am not an expert on this but this method works for me , if you think you are an expert explain,why this works?
