### ISSUE TITLE
Fingerprint not working

### ISSUE THREAD

**Issue by harshit-ig** [ItsVixano-releases/LineageOS_ysl#5]
The fingerprint option is completely missing after this update

**Comment by ItsVixano** [comment]
mind i ask which fp your phone use ?? (goodix / fpc)
also drop some logs

**Comment by ItsVixano** [comment]
nvm i found a little derp on the device tree related to goodix fp, i'll push an hotfix ASAP

**Comment by ItsVixano** [comment]
mind checking if the latest ota works fine ?

**Comment by harshit-ig** [comment]
Yes after installing the latest version with hotfix, it's started working again but i had to download it manually from the GitHub and install using the local update option because it was not showing in the ota update. But it's working perfectly fine now. Thanks for the quick response 😅
