### ISSUE TITLE
Redmi S2 Not Starting After Restart 

### ISSUE THREAD

**Issue by ebnurrahim** [ItsVixano-releases/LineageOS_ysl#6]
I FLASHED LINEAGEOS 20 ON 12 MAY. NOW I GOT AN ISSUE. MY PHONE SUDDENLY SWITCHED OFF AND TRIED TO RESTART ITSELF. BUT IT CONTINUES TO FAIL AND TRYING TO GET INTO THE BOOT.AFTER 5/10 MINUTES DEVICE GETS NORMAL. WHAT SHOULD I DO NOW? THIS PROBLEM IS JUST HEADACHE.

**Comment by ItsVixano** [comment]
Have you flashed anything unusual other than Los + MTG ?? (With that i meant magisk, DFE, and some random modules)

**Comment by ebnurrahim** [comment]
I didn't rooted my device and i also didn't used any unnecessary flashes.

**Comment by ebnurrahim** [comment]
Should i have to root my redmi s2 phone? Will it fix this problem. Just answer please.

**Comment by ItsVixano** [comment]
> Should i have to root my redmi s2 phone? Will it fix this problem. Just answer please.

make sure you followed correctly the installation guide i linked 

guide.itsvixano.me

**Comment by ebnurrahim** [comment]
Can't i use custom recovery while flashing and keep it?
