### ISSUE TITLE
Mi Remote app not working 

### ISSUE THREAD

**Issue by IAMSDR** [ItsVixano-releases/LineageOS_ysl#8]
It's crashing and cause endless vibration and poweroff automatically after 5-6 seconds. please fix this in next update.

Thank you so much for this rom and support ♥️

**Comment by ItsVixano** [comment]
Hi, i confirm this is indeed an issue, i'll take a look at it right now

**Comment by ItsVixano** [comment]
This issue has been addressed with [`android_kernel_xiaomi_msm8953 67eaec7955df4f7886fcee8186dc48776a361b27`](https://github.com/xiaomi-msm8953-devs/android_kernel_xiaomi_msm8953/commit/67eaec7955df4f7886fcee8186dc48776a361b27)

You can either wait for the next build or flash this [boot.img](https://pixeldrain.com/api/file/ux8rSbCa?download) for now

**Comment by IAMSDR** [comment]
Thank u , i wait for next build 🙂.
